name: Release latest

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  packages: write

jobs:
  container-push-latest:
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: datumbase
      tag: latest
      dockerfile_path: .
